import { createBrowserClient } from '@supabase/ssr';
// Use the extended Database type that includes SynqForge tables.  The
// autogenerated `types_db.ts` file does not include our custom tables
// (organisations, projects, stories, etc.), so we import from
// '@/types/extended-db' instead.  If you regenerate types via Supabase
// CLI in the future, you can point back to types_db.ts.
import type { Database } from '@/types/extended-db';

// Define a function to create a Supabase client for client-side operations
export const createClient = () =>
  createBrowserClient<Database>(
    // Pass Supabase URL and anonymous key from the environment to the client
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  );
