name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Lint & Typecheck
        run: pnpm lint && pnpm typecheck
      - name: Build (Demo Mode)
        run: pnpm build
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_FREELANCER_MODE: 'true'
          DISABLE_BILLING: 'true'
      - name: Unit tests
        run: pnpm test
      - name: E2E tests (Demo Mode)
        run: |
          npx playwright install --with-deps
          pnpm test:e2e
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          NEXT_PUBLIC_FREELANCER_MODE: 'true'
          DISABLE_BILLING: 'true'


